name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: [FlexCore]
softdepend: []
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
commands:
  flexchannel:
    aliases: [channel, channels, ch]
  flexchatspy:
    aliases: [chatspy, socialspy]
  flexignore:
    aliases: [ignore, block]
  flexunignore:
    aliases: [unignore, unblock]
  flexmessage:
    aliases: [message, msg, m, pm, tell, t, whisper, whisp, w]
  flexreply:
    aliases: [reply, r]

permissions:
  ##########
  # Groups #
  ##########
  flexchat.admin:
    default: op
    children:
      flexchat.chat.color: true
      flexchat.chat.format: true
      flexchat.chat.magic: true
      flexchat.chat.spy: true
      flexchat.chat.spy.toggle: true
      flexchat.chat.spy.toggle.other: true
      flexchat.chat.spy.persistent: true
      flexchat.channel.view.bypass: true
      flexchat.ignore.bypass: true

  flexchat.user:
    default: true
    children:
      flexchat.ignore: true
      flexchat.message: true

  #########
  # Nodes #
  #########
  flexchat.chat.color:
    description: 'Ability to use color codes in chat messages'
    default: false
  flexchat.chat.format:
    description: 'Ability to use formatting codes in chat messages'
    default: false
  flexchat.chat.magic:
    description: 'Ability to use the magic formatting code in chat messages'
    default: false

  flexchat.chat.spy.toggle:
    description: 'Ability to toggle spy mode'
    default: false
  flexchat.chat.spy.toggle.other:
    description: 'Ability to toggle other player''s spy mode'
    default: false
  flexchat.chat.spy.persistent:
    description: 'Keep chat spy mode through server restarts'
    default: false

  flexchat.ignore:
    description: 'Ability to ignore another player and not receive messages from them'
    default: false
  flexchat.ignore.bypass:
    description: 'Ability to bypass being ignored by another player'
    default: false

  flexchat.message:
    description: 'Ability to use private messaging'
    default: false

  flexchat.channel.view.bypass:
    description: 'Ability to view channels on the channel list command even if they don''t normally allow it'
    default: false