name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: [FlexLib]
softdepend: [mcMMO, Towny]
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
commands:
  channel:
    description: 'Base channel command and quick channel switcher'
    aliases: [fchannel, channels, ch]
  chatspy:
    description: 'Base chat spy command'
    aliases: [fchatspy, socialspy]
  ignore:
    description: 'Ignore a player'
    aliases: [fignore, block]
  unignore:
    description: 'Unignore a player'
    aliases: [funignore, unblock]
  message:
    description: 'Private message a player'
    aliases: [fmessage, msg, m, pm, tell, t, whisper, whisp, w]
  reply:
    description: 'Quick reply to the last player messaged'
    aliases: [fr, r]

permissions:
  ##########
  # Groups #
  ##########
  flexchat.admin:
    default: op
    children:
      flexchat.color: true
      flexchat.format: true
      flexchat.list.instance.all: true
      flexchat.magic: true
      flexchat.bypass.ignore: true
      flexchat.bypass.join: true
      flexchat.bypass.mute: true
      flexchat.bypass.view: true
      flexchat.kick: true
      flexchat.spy: true
      flexchat.spy.persistent: true
      flexchat.who.other: true

  flexchat.user:
    default: true
    children:
      flexchat.list: true
      flexchat.list.instance: true
      flexchat.ignore: true
      flexchat.message: true
      flexchat.who: true

  #########
  # Nodes #
  #########
  flexchat.color:
    description: 'Ability to use color codes in chat messages'
    default: false
  flexchat.format:
    description: 'Ability to use formatting codes in chat messages'
    default: false
  flexchat.magic:
    description: 'Ability to use the magic formatting code in chat messages'
    default: false

  flexchat.spy:
    description: 'Ability to use spy mode'
    default: false
  flexchat.spy.persistent:
    description: 'Keep chat spy settings through server restarts and logging off'
    default: false

  flexchat.bypass.ignore:
    description: 'Ability to bypass being ignored by another player'
    default: false
  flexchat.bypass.join:
    description: 'Ability to join any channel instance'
    default: false
  flexchat.view.bypass:
    description: 'Ability to view channels on the channel list even if they don''t normally allow it'
    default: false

  flexchat.list:
    description: 'Ability to list channels'
    default: false
  flexchat.list.instance:
    description: 'Ability to list joined channel instances for a channel'
    default: false
  flexchat.list.instance.all:
    description: 'Ability to list all channel instances for a channel'
    default: false

  flexchat.ignore:
    description: 'Ability to ignore another player and not receive messages from them'
    default: false

  flexchat.kick:
    description: 'Ability to kick a player from a channel'
    default: false

  flexchat.message:
    description: 'Ability to use private messaging'
    default: false

  flexchat.who:
    description: 'Ability to view who is in a channel'
    default: false
  flexchat.who.other:
    description: 'Ability to view who is in a channel even if you are not in the channel'
    default: false