# Global channel formats
global formats:
  vanilla:
    default: '<{NAME}> {MESSAGE}'

channel prefix:
  format: '&8[{CHCOLOR}{CHTAG}&8]&f '
  enabled: true
  force state: false

# Private message formats
message formats:
  default: '&f[&7{SENDER} &f\u27A1 &7{RECEIVER}&f] &7{MESSAGE}'

# Provider configuration
#providers:
#  vanilla:
#    formats:
