command spy:
  format: '&4[&cSPY&4] &7{SENDER}&8: &7{COMMAND}'
  commands:
    - '/t'
    - '/tell'
    - '/msg'
    - '/m'
    - '/pm'
    - '/whisper'
    - '/whisp'
    - '/w'
    - '/reply'
    - '/r'
channel spy:
  channel format: '&4[&cSPY&4] &8[&7{CHANNEL}&8] &7{SENDER}&8: &7{MESSAGE}'
  instance format: '&4[&cSPY&4] &8[&7{CHANNEL}&8:&7{INSTANCE}&8] &7{SENDER}&8: &7{MESSAGE}'